name = "TMO22 Problem 1 in LEAN"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["«TMO22 Problem 1 in LEAN»"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "«TMO22 Problem 1 in LEAN»"
